name: Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Put Firmare Link'
        required: true

env:
  LINK: ${{ github.event.inputs.link }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TZ: Asia/Jakarta

jobs:
  dumper:
      runs-on: ubuntu-latest
      container:
          image: renayura/archlinux:latest

      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup configs
        run: |
             bash setup.sh
             git config --global user.name "Renayura"
             git config --global user.email "renayura@proton.me"
             echo "$GH_TOKEN" > .githubtoken
             echo "$TG_TOKEN" > .tgtoken
      - name: Start dumping firmware
        run: |
             bash dumpyara.sh $LINK

